### ISSUE TITLE
`wget -c` vs. `curl -C -`?

### ISSUE THREAD

**Issue by postmodern** [bagder/docs#5]
> ~~* Wget enables more features by default: cookies, redirect-following, time stamping from the remote resource etc. With curl most of those features need to be explicitly enabled.~~
> * Its ability to recover from a prematurely broken transfer and continue downloading has no counterpart in curl.

Correct me if I'm wrong, but I think `curl` also has this functionality? I have successfully used `curl -C -` as an equivalent to `wget -c` in shell scripts before. Or are you referring to other retry mechanisms in `wget`?

**Comment by bagder** [comment]
> Wget enables more features by default

I don't think this is debatable, and it isn't just about resuming transfers it is also about cookies, redirect-following, time stamping etc as the quote says.

Both wget and curl feature and support file transfer resumes, yes, but I don't think we even mention resumes in that page. Should we? Wouldn't that basically become just another feature both have?

**Comment by postmodern** [comment]
Oh darn it, I copied the wrong text!

> Its ability to recover from a prematurely broken transfer and continue downloading has no counterpart in curl.

Wouldn't counterpart be `curl -C -`?

**Comment by bagder** [comment]
Ah. Well curl can resume a transfer, but what I was thinking about when I wrote that is problems when for example a transfer gets aborted in the middle so that there's a partial transfer on the local disk.

In several cases wget will then be able to retry and resume the remainder of that file completely on its own while with curl you'd have to notice the situation and make an active second command line yourself to make it get the remainder of the file.
